services:
  - type: web
    name: ai-code-review-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: sh -c "python manage.py migrate && gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: FRONTEND_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: BACKEND_PUBLIC_URL
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ai-code-review-db
          property: connectionString
      - key: AI_SERVICE_HOSTPORT
        fromService:
          type: web
          name: ai-code-review-ai
          property: hostport

  - type: web
    name: ai-code-review-ai
    runtime: python
    plan: free
    rootDir: ai_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ANTHROPIC_API_KEY
        sync: false

databases:
  - name: ai-code-review-db
    plan: free
    databaseName: codereviewer
    user: codereviewer
